use std::{fs::File, io::Write, env};

use dotenvy::dotenv;

fn main() {
    println!("cargo:rerun-if-changed=.env");
    
    let dest_path = "./src/env.rs";
    let mut file = File::create(&dest_path).unwrap();
    dotenv().expect(".env file not found");

    file.write_all(b"// This file is automatically generated by build.rs\n\n")
        .unwrap();

    for (key, value) in env::vars() {
        if !key.starts_with("APP_") {
            continue;
        }

        let line = format!(
            "pub const {}: &'static str = \"{}\";\n",
            key,
            value.replace("\"", "\\\"")
        );
        file.write_all(line.as_bytes()).unwrap();
    }
}