[package]
name = "babs_frontend"
version = "0.1.0"
authors = ["Traxx186"]
edition = "2021"
rust-version = "1.70"
readme = "README.md"

[dependencies]
anyhow = "1.0.75"
babs = { version = "0.1.0", path = ".." }
getrandom = { version = "0.2.10", features = ["js"] }
gloo = "0.10.0"
log = "0.4.20"
reqwasm = "0.5.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2.84"
wasm-logger = "0.2.0"
wasm-bindgen-futures = "0.4.34"
web-sys = { version = "0.3.61", features = ["HtmlInputElement", "Window", "HtmlDocument"] }
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17.0"