[package]
name = "babs_frontend"
version = "0.1.0"
authors = ["Traxx186"]
edition = "2021"
rust-version = "1.70"
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.75"
babs = { version = "0.1.0", path = ".." }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
wasm-bindgen = "0.2.87"
yew = "0.20.0"
yew-router = "0.17.0"