[package]
name = "bonk-inc-backend"
version = "0.1.0"
authors = ["Traxx186"]
edition = "2021"
rust-version = "1.70"
readme = "README.md"

[dependencies]
actix-web = "4.3"
chrono = { version = "0.4.23", features = ["serde"] }
diesel = { version = "2.1", features = ["postgres", "chrono", "uuid", "r2d2"] }
dotenvy = "0.15"
env_logger = "0.10"
log = "0.4"
r2d2 = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.4", features = ["serde", "v4"] }