[package]
name = "bonk-inc-backend"
version = "0.1.0"
authors = ["Traxx186"]
edition = "2021"
rust-version = "1.70"
readme = "README.md"

[dependencies]
actix-web = "4.3"
chrono = { version = "0.4.23", features = ["serde"] }
dotenvy = "0.15"
env_logger = "0.10"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-async-std", "tls-native-tls", "postgres", "uuid", "chrono"] }
uuid = { version = "1.4", features = ["serde", "v4"] }