[package]
name = "babs_backend"
version = "0.1.0"
authors = ["Traxx186"]
edition = "2021"
rust-version = "1.76"
readme = "README.md"

[[bin]]
name = "bonk-inc-backend"
path = "src/main.rs"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.5"
actix-web = "4.5.1"
babs = { version = "0.1.0", path = "..", features = ["backend"] }
chrono = { version = "0.4.35", features = ["serde"] }
derive_more = "0.99.17"
diesel = { version = "2.1.4", features = ["postgres", "chrono", "uuid", "r2d2"] }
diesel_migrations = "2.1.0"
dotenvy = "0.15.7"
env_logger = "0.11.3"
futures-util = "0.3.30"
jsonwebtoken = "9.2.0"
log = "0.4.21"
oauth2 = "4.4.2"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
uuid = { version = "1.7.0", features = ["serde", "v4"] }
validator = { version = "0.17.0", features = ["derive"] }