[package]
name = "babs_backend"
version = "0.1.0"
authors = ["Traxx186"]
edition = "2021"
rust-version = "1.74"
readme = "README.md"

[[bin]]
name = "bonk-inc-backend"
path = "src/main.rs"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-web = "4.4.0"
babs = { version = "0.1.0", path = "..", features = ["backend"] }
chrono = { version = "0.4.30", features = ["serde"] }
derive_more = "0.99.17"
diesel = { version = "2.1.1", features = ["postgres", "chrono", "uuid", "r2d2"] }
diesel_migrations = "2.1.0"
dotenvy = "0.15.7"
env_logger = "0.10.0"
futures-util = "0.3.28"
jsonwebtoken = "8.3.0"
log = "0.4.20"
oauth2 = "4.4.1"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive"] }