version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    container_name: bonk-inc-backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      APP_PORT: "0.0.0.0"